name = "StarMap.SimpleMod"

[StarMap]
EntryAssembly = "StarMap.SimpleMod"

[[StarMap.ModDependencies]]
ModId = "StarMap.SimpleMod2"
Optional = false
ImportedAssemblies = [
    "StarMap.SimpleMod.Dependency"
]