<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="StarMap.API" Version="0.3.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\StarMap.SimpleMod.Dependency\StarMap.SimpleMod.Dependency.csproj" />
  </ItemGroup>

	<ItemGroup>
		<Reference Include="..\..\Import\KSA.dll">
			<ExcludeAssets>runtime</ExcludeAssets>
		</Reference>
		<Reference Include="..\..\Import\Brutal.ImGui.dll">
			<ExcludeAssets>runtime</ExcludeAssets>
		</Reference>
		<Reference Include="..\..\Import\Brutal.ImGui.Extensions.dll">
			<ExcludeAssets>runtime</ExcludeAssets>
		</Reference>
		<Reference Include="..\..\Import\Brutal.Core.Numerics.dll">
			<ExcludeAssets>runtime</ExcludeAssets>
		</Reference>
		<Reference Include="..\..\Import\Brutal.Glfw.dll">
			<ExcludeAssets>runtime</ExcludeAssets>
		</Reference>
	</ItemGroup>

	<ItemGroup>
	  <None Update="mod.toml">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	</ItemGroup>

</Project>
